/**
 * WMS Seed Script
 * Run: npm run seed
 *
 * Seeds:
 * 1. Default Super Admin user
 * 2. Warehouse locations (26 zones A–Z)
 * 3. Product catalog sample (3 per category × 26 categories = 78 products)
 */

import "dotenv/config";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

// ── DB ──────────────────────────────────────────────────────────────────────
const uri = process.env.MONGODB_URI?.trim().replace(/^["']|["']$/g, "") ?? "";
if (!uri || uri.includes("<name>")) {
  console.error("Set MONGODB_URI in .env before seeding");
  process.exit(1);
}

async function connect() {
  await mongoose.connect(uri);
  console.log("Connected to MongoDB");
}

// ── Models ───────────────────────────────────────────────────────────────────
import { WarehouseUser } from "../shared/models/WarehouseUser";
import { WarehouseLocation } from "../shared/models/WarehouseLocation";
import { WMSProductCatalog } from "../shared/models/WMSProductCatalog";

// ── Zone definitions from the FR3SH 3000-product catalog ─────────────────────
const ZONES = [
  { code: "A", name: "Rice & Grains", type: "Ambient" },
  { code: "B", name: "Millets", type: "Ambient" },
  { code: "C", name: "Fresh Fruits", type: "Cold" },
  { code: "D", name: "Vegetables", type: "Cold" },
  { code: "E", name: "Leafy Greens", type: "Cold" },
  { code: "F", name: "Beans & Fresh Legumes", type: "Cold" },
  { code: "G", name: "Pulses & Lentils", type: "Ambient" },
  { code: "H", name: "Culinary Herbs", type: "Ambient" },
  { code: "I", name: "Spices", type: "Ambient" },
  { code: "J", name: "Seeds", type: "Ambient" },
  { code: "K", name: "Dry Fruits & Nuts", type: "Ambient" },
  { code: "L", name: "Cold-Pressed Oils", type: "Cool" },
  { code: "M", name: "Natural Sweeteners", type: "Ambient" },
  { code: "N", name: "Flours & Powders", type: "Ambient" },
  { code: "O", name: "Organic Beverages", type: "Ambient" },
  { code: "P", name: "Pickles & Ferments", type: "Cool" },
  { code: "Q", name: "Dairy", type: "Refrigerated" },
  { code: "R", name: "Eggs", type: "Refrigerated" },
  { code: "S", name: "Meat & Poultry", type: "Refrigerated" },
  { code: "T", name: "Seafood", type: "Refrigerated" },
  { code: "U", name: "Mushrooms", type: "Cold" },
  { code: "V", name: "Microgreens & Sprouts", type: "Cold" },
  { code: "W", name: "Edible Flowers", type: "Cold" },
  { code: "X", name: "Processed Foods", type: "Ambient" },
  { code: "Y", name: "Ready-to-Cook Mixes", type: "Ambient" },
  { code: "Z", name: "Condiments & Misc Food", type: "Ambient" },
];

const TEMP_MAP: Record<string, string> = {
  Ambient: "18–25°C",
  Cold: "2–8°C",
  Cool: "10–18°C",
  Refrigerated: "1–4°C",
  Frozen: "-18°C",
};

// ── Sample products (3 per zone from FR3SH 3000-item catalog) ─────────────────
const SEED_PRODUCTS = [
  { skuPrefix: "FR3SH-A-0001", zoneCode: "A", category: "Rice & Grains", subcategory: "Rice", productName: "Organic Rice - Whole Grain - Premium", grade: "Premium", form: "Whole Grain", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1006/1001", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Assam", supplierType: "Farmer/FPO", barcodeSkuCode: "A0000001", minimumOrderQty: 5, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, residue test, visual grading, moisture check, batch traceability" },
  { skuPrefix: "FR3SH-A-0002", zoneCode: "A", category: "Rice & Grains", subcategory: "Rice", productName: "Organic Rice - Whole Grain - Standard", grade: "Standard", form: "Whole Grain", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1006/1001", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "A0000002", minimumOrderQty: 10, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, residue test, visual grading, moisture check" },
  { skuPrefix: "FR3SH-A-0050", zoneCode: "A", category: "Rice & Grains", subcategory: "Wheat", productName: "Organic Wheat - Hard - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1001", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Punjab", supplierType: "Farmer/FPO", barcodeSkuCode: "A0000050", minimumOrderQty: 10, recommendedPackaging: "Jute Bag", qualityChecks: "Moisture, residue test, batch traceability" },
  { skuPrefix: "FR3SH-B-0001", zoneCode: "B", category: "Millets", subcategory: "Foxtail Millet", productName: "Organic Foxtail Millet - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "1008", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Andhra Pradesh", supplierType: "Farmer/FPO", barcodeSkuCode: "B0000001", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, residue test" },
  { skuPrefix: "FR3SH-B-0050", zoneCode: "B", category: "Millets", subcategory: "Little Millet", productName: "Organic Little Millet - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "1008", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "B0000050", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Moisture, visual grading, batch traceability" },
  { skuPrefix: "FR3SH-B-0100", zoneCode: "B", category: "Millets", subcategory: "Finger Millet", productName: "Organic Finger Millet (Ragi) - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "1008", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Karnataka", supplierType: "Farmer/FPO", barcodeSkuCode: "B0000100", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-C-0001", zoneCode: "C", category: "Fresh Fruits", subcategory: "Mango", productName: "Organic Mango - Alphonso - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 14, hsnCode: "0804", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: true, mainSeason: "Apr–Jun", stateAvailability: "Maharashtra", supplierType: "Farmer/FPO", barcodeSkuCode: "C0000001", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, visual grading, freshness check" },
  { skuPrefix: "FR3SH-C-0050", zoneCode: "C", category: "Fresh Fruits", subcategory: "Banana", productName: "Organic Banana - Robusta - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 7, hsnCode: "0803", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Tamil Nadu", supplierType: "Farmer/FPO", barcodeSkuCode: "C0000050", minimumOrderQty: 10, recommendedPackaging: "Crate", qualityChecks: "Residue test, freshness, bruise check" },
  { skuPrefix: "FR3SH-C-0100", zoneCode: "C", category: "Fresh Fruits", subcategory: "Guava", productName: "Organic Guava - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 10, hsnCode: "0804", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Allahabad", supplierType: "Farmer/FPO", barcodeSkuCode: "C0000100", minimumOrderQty: 5, recommendedPackaging: "Crate", qualityChecks: "Residue test, visual grading" },
  { skuPrefix: "FR3SH-D-0001", zoneCode: "D", category: "Vegetables", subcategory: "Tomato", productName: "Organic Tomato - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 14, hsnCode: "0702", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Maharashtra", supplierType: "Farmer/FPO", barcodeSkuCode: "D0000001", minimumOrderQty: 10, recommendedPackaging: "Crate", qualityChecks: "Residue test, visual grading, freshness" },
  { skuPrefix: "FR3SH-D-0050", zoneCode: "D", category: "Vegetables", subcategory: "Onion", productName: "Organic Onion - Red - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 30, hsnCode: "0703", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: false, seasonal: false, mainSeason: "Year-round", stateAvailability: "Maharashtra", supplierType: "Farmer/FPO", barcodeSkuCode: "D0000050", minimumOrderQty: 10, recommendedPackaging: "Jute Net Bag", qualityChecks: "Visual grading, moisture check" },
  { skuPrefix: "FR3SH-D-0080", zoneCode: "D", category: "Vegetables", subcategory: "Carrot", productName: "Organic Carrot - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 21, hsnCode: "0706", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Ooty, TN", supplierType: "Farmer/FPO", barcodeSkuCode: "D0000080", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, visual grading, freshness" },
  { skuPrefix: "FR3SH-E-0001", zoneCode: "E", category: "Leafy Greens", subcategory: "Spinach", productName: "Organic Spinach - Standard", grade: "Standard", form: "Loose", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "E0000001", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, freshness, moisture check" },
  { skuPrefix: "FR3SH-E-0020", zoneCode: "E", category: "Leafy Greens", subcategory: "Moringa Leaves", productName: "Organic Moringa Leaves - Premium", grade: "Premium", form: "Loose", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Tamil Nadu", supplierType: "Farmer/FPO", barcodeSkuCode: "E0000020", minimumOrderQty: 2, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, freshness" },
  { skuPrefix: "FR3SH-E-0040", zoneCode: "E", category: "Leafy Greens", subcategory: "Fenugreek Leaves", productName: "Organic Fenugreek Leaves - Standard", grade: "Standard", form: "Loose", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "E0000040", minimumOrderQty: 2, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, freshness" },
  { skuPrefix: "FR3SH-F-0001", zoneCode: "F", category: "Beans & Fresh Legumes", subcategory: "French Beans", productName: "Organic French Beans - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 7, hsnCode: "0708", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Ooty, TN", supplierType: "Farmer/FPO", barcodeSkuCode: "F0000001", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, visual grading" },
  { skuPrefix: "FR3SH-F-0030", zoneCode: "F", category: "Beans & Fresh Legumes", subcategory: "Green Peas", productName: "Organic Green Peas - Premium", grade: "Premium", form: "Pod", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 7, hsnCode: "0708", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: true, mainSeason: "Nov–Feb", stateAvailability: "UP", supplierType: "Farmer/FPO", barcodeSkuCode: "F0000030", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, freshness, visual grading" },
  { skuPrefix: "FR3SH-F-0060", zoneCode: "F", category: "Beans & Fresh Legumes", subcategory: "Cluster Beans", productName: "Organic Cluster Beans - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0708", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "F0000060", minimumOrderQty: 5, recommendedPackaging: "Clamshell", qualityChecks: "Residue test, freshness" },
  { skuPrefix: "FR3SH-G-0001", zoneCode: "G", category: "Pulses & Lentils", subcategory: "Toor Dal", productName: "Organic Toor Dal - Premium", grade: "Premium", form: "Split", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0713", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Maharashtra", supplierType: "Farmer/FPO", barcodeSkuCode: "G0000001", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-G-0050", zoneCode: "G", category: "Pulses & Lentils", subcategory: "Moong Dal", productName: "Organic Moong Dal - Green - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0713", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "G0000050", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture" },
  { skuPrefix: "FR3SH-G-0120", zoneCode: "G", category: "Pulses & Lentils", subcategory: "Chana Dal", productName: "Organic Chana Dal - Premium", grade: "Premium", form: "Split", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0713", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "MP", supplierType: "Farmer/FPO", barcodeSkuCode: "G0000120", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-H-0001", zoneCode: "H", category: "Culinary Herbs", subcategory: "Tulsi", productName: "Organic Tulsi - Dried - Premium", grade: "Premium", form: "Dried", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Uttarakhand", supplierType: "Farmer/FPO", barcodeSkuCode: "H0000001", minimumOrderQty: 50, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-H-0020", zoneCode: "H", category: "Culinary Herbs", subcategory: "Rosemary", productName: "Organic Rosemary - Dried - Standard", grade: "Standard", form: "Dried", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Himachal", supplierType: "Farmer/FPO", barcodeSkuCode: "H0000020", minimumOrderQty: 50, recommendedPackaging: "Paper Pouch", qualityChecks: "Moisture, visual grading" },
  { skuPrefix: "FR3SH-H-0040", zoneCode: "H", category: "Culinary Herbs", subcategory: "Basil", productName: "Organic Basil - Dried - Premium", grade: "Premium", form: "Dried", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Tamil Nadu", supplierType: "Farmer/FPO", barcodeSkuCode: "H0000040", minimumOrderQty: 50, recommendedPackaging: "Glass Jar", qualityChecks: "Moisture, visual grading, organic certificate" },
  { skuPrefix: "FR3SH-I-0001", zoneCode: "I", category: "Spices", subcategory: "Turmeric", productName: "Organic Turmeric - Whole - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "I0000001", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, residue test, visual grading, moisture check" },
  { skuPrefix: "FR3SH-I-0050", zoneCode: "I", category: "Spices", subcategory: "Black Pepper", productName: "Organic Black Pepper - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0904", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Kerala", supplierType: "Farmer/FPO", barcodeSkuCode: "I0000050", minimumOrderQty: 2, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-I-0100", zoneCode: "I", category: "Spices", subcategory: "Cumin", productName: "Organic Cumin - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0909", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "I0000100", minimumOrderQty: 2, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-J-0001", zoneCode: "J", category: "Seeds", subcategory: "Sesame Seeds", productName: "Organic Sesame Seeds - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1207", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "J0000001", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-J-0030", zoneCode: "J", category: "Seeds", subcategory: "Flax Seeds", productName: "Organic Flax Seeds - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1204", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "MP", supplierType: "Farmer/FPO", barcodeSkuCode: "J0000030", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture" },
  { skuPrefix: "FR3SH-J-0060", zoneCode: "J", category: "Seeds", subcategory: "Chia Seeds", productName: "Organic Chia Seeds - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1207", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "J0000060", minimumOrderQty: 2, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-K-0001", zoneCode: "K", category: "Dry Fruits & Nuts", subcategory: "Almond", productName: "Organic Almond - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0802", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "J&K", supplierType: "Farmer/FPO", barcodeSkuCode: "K0000001", minimumOrderQty: 2, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-K-0030", zoneCode: "K", category: "Dry Fruits & Nuts", subcategory: "Cashew", productName: "Organic Cashew W320 - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "0801", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Goa, Kerala", supplierType: "Farmer/FPO", barcodeSkuCode: "K0000030", minimumOrderQty: 2, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-K-0060", zoneCode: "K", category: "Dry Fruits & Nuts", subcategory: "Dates Dry", productName: "Organic Medjool Dates - Premium", grade: "Premium", form: "Dried", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "0804", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "K0000060", minimumOrderQty: 2, recommendedPackaging: "Glass Jar", qualityChecks: "Moisture, visual grading, batch traceability" },
  { skuPrefix: "FR3SH-L-0001", zoneCode: "L", category: "Cold-Pressed Oils", subcategory: "Groundnut Oil", productName: "Organic Cold-Pressed Groundnut Oil - Premium", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Cool", shelfLifeDays: 180, hsnCode: "1508", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "L0000001", minimumOrderQty: 5, recommendedPackaging: "Glass Bottle", qualityChecks: "Organic certificate, peroxide value, FFA test, batch traceability" },
  { skuPrefix: "FR3SH-L-0030", zoneCode: "L", category: "Cold-Pressed Oils", subcategory: "Sesame Oil", productName: "Organic Cold-Pressed Sesame Oil - Premium", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Cool", shelfLifeDays: 180, hsnCode: "1515", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "L0000030", minimumOrderQty: 2, recommendedPackaging: "Glass Bottle", qualityChecks: "Peroxide value, FFA test, organic certificate" },
  { skuPrefix: "FR3SH-L-0060", zoneCode: "L", category: "Cold-Pressed Oils", subcategory: "Coconut Oil", productName: "Organic Cold-Pressed Coconut Oil - Premium", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Cool", shelfLifeDays: 365, hsnCode: "1513", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Kerala", supplierType: "Farmer/FPO", barcodeSkuCode: "L0000060", minimumOrderQty: 2, recommendedPackaging: "Glass Bottle", qualityChecks: "Peroxide value, FFA test, organic certificate" },
  { skuPrefix: "FR3SH-M-0001", zoneCode: "M", category: "Natural Sweeteners", subcategory: "Jaggery", productName: "Organic Jaggery - Block - Premium", grade: "Premium", form: "Block", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1701", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Karnataka", supplierType: "Farmer/FPO", barcodeSkuCode: "M0000001", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-M-0030", zoneCode: "M", category: "Natural Sweeteners", subcategory: "Raw Honey", productName: "Organic Raw Honey - Premium", grade: "Premium", form: "Liquid", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "0409", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Sundarbans", supplierType: "Farmer/FPO", barcodeSkuCode: "M0000030", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, moisture, HMF test, batch traceability" },
  { skuPrefix: "FR3SH-M-0060", zoneCode: "M", category: "Natural Sweeteners", subcategory: "Coconut Sugar", productName: "Organic Coconut Sugar - Standard", grade: "Standard", form: "Granules", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "1701", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Tamil Nadu", supplierType: "Farmer/FPO", barcodeSkuCode: "M0000060", minimumOrderQty: 2, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Moisture, organic certificate" },
  { skuPrefix: "FR3SH-N-0001", zoneCode: "N", category: "Flours & Powders", subcategory: "Rice Flour", productName: "Organic Rice Flour - Premium", grade: "Premium", form: "Powder", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "1102", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana", supplierType: "Farmer/FPO", barcodeSkuCode: "N0000001", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-N-0030", zoneCode: "N", category: "Flours & Powders", subcategory: "Ragi Flour", productName: "Organic Ragi Flour - Premium", grade: "Premium", form: "Powder", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "1102", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Karnataka", supplierType: "Farmer/FPO", barcodeSkuCode: "N0000030", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture" },
  { skuPrefix: "FR3SH-N-0060", zoneCode: "N", category: "Flours & Powders", subcategory: "Besan", productName: "Organic Besan (Chickpea Flour) - Premium", grade: "Premium", form: "Powder", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "1106", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "N0000060", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Moisture, organic certificate" },
  { skuPrefix: "FR3SH-O-0001", zoneCode: "O", category: "Organic Beverages", subcategory: "Green Tea", productName: "Organic Green Tea - Premium", grade: "Premium", form: "Loose", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "0902", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Darjeeling", supplierType: "Farmer/FPO", barcodeSkuCode: "O0000001", minimumOrderQty: 100, recommendedPackaging: "Tin", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-O-0030", zoneCode: "O", category: "Organic Beverages", subcategory: "Coffee Beans", productName: "Organic Arabica Coffee Beans - Premium", grade: "Premium", form: "Whole Bean", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0901", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Coorg, Karnataka", supplierType: "Farmer/FPO", barcodeSkuCode: "O0000030", minimumOrderQty: 250, recommendedPackaging: "Valve Bag", qualityChecks: "Organic certificate, moisture, visual grading, cupping test" },
  { skuPrefix: "FR3SH-O-0060", zoneCode: "O", category: "Organic Beverages", subcategory: "Amla Juice", productName: "Organic Amla Juice - Standard", grade: "Standard", form: "Liquid", defaultUnit: "litre", storageType: "Ambient", shelfLifeDays: 90, hsnCode: "2009", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "O0000060", minimumOrderQty: 1, recommendedPackaging: "Glass Bottle", qualityChecks: "Organic certificate, pH, brix value" },
  { skuPrefix: "FR3SH-P-0001", zoneCode: "P", category: "Pickles & Ferments", subcategory: "Mango Pickle", productName: "Organic Mango Pickle - Traditional", grade: "Standard", form: "Processed", defaultUnit: "kg", storageType: "Cool", shelfLifeDays: 365, hsnCode: "2001", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Andhra Pradesh", supplierType: "Farmer/FPO", barcodeSkuCode: "P0000001", minimumOrderQty: 2, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, acidity test, preservative-free check" },
  { skuPrefix: "FR3SH-P-0020", zoneCode: "P", category: "Pickles & Ferments", subcategory: "Lemon Pickle", productName: "Organic Lemon Pickle - Premium", grade: "Premium", form: "Processed", defaultUnit: "kg", storageType: "Cool", shelfLifeDays: 365, hsnCode: "2001", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Rajasthan", supplierType: "Farmer/FPO", barcodeSkuCode: "P0000020", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, acidity test" },
  { skuPrefix: "FR3SH-P-0040", zoneCode: "P", category: "Pickles & Ferments", subcategory: "Sauerkraut", productName: "Organic Sauerkraut - Standard", grade: "Standard", form: "Fermented", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 90, hsnCode: "2001", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "P0000040", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "pH test, live cultures check, organic certificate" },
  { skuPrefix: "FR3SH-Q-0001", zoneCode: "Q", category: "Dairy", subcategory: "Milk", productName: "Organic Whole Milk - A2 Premium", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Refrigerated", shelfLifeDays: 3, hsnCode: "0401", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat, Haryana", supplierType: "Farmer/FPO", barcodeSkuCode: "Q0000001", minimumOrderQty: 1, recommendedPackaging: "HDPE Bottle", qualityChecks: "Organic certificate, fat content, SNF, MBRT test" },
  { skuPrefix: "FR3SH-Q-0010", zoneCode: "Q", category: "Dairy", subcategory: "Ghee", productName: "Organic Desi Cow Ghee - Premium", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0405", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "Q0000010", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, fat content, Reichert-Meissl value" },
  { skuPrefix: "FR3SH-Q-0020", zoneCode: "Q", category: "Dairy", subcategory: "Paneer", productName: "Organic Paneer - Premium", grade: "Premium", form: "Block", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 7, hsnCode: "0406", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Punjab, Gujarat", supplierType: "Farmer/FPO", barcodeSkuCode: "Q0000020", minimumOrderQty: 0.5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture, microbiological check" },
  { skuPrefix: "FR3SH-R-0001", zoneCode: "R", category: "Eggs", subcategory: "Free-range Chicken Eggs", productName: "Organic Free-Range Chicken Eggs", grade: "Premium", form: "Whole", defaultUnit: "dozen", storageType: "Refrigerated", shelfLifeDays: 21, hsnCode: "0407", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "R0000001", minimumOrderQty: 1, recommendedPackaging: "Clamshell", qualityChecks: "Organic certificate, freshness float test, visual grading" },
  { skuPrefix: "FR3SH-R-0010", zoneCode: "R", category: "Eggs", subcategory: "Country Chicken Eggs", productName: "Country Chicken Eggs - Naati", grade: "Standard", form: "Whole", defaultUnit: "dozen", storageType: "Refrigerated", shelfLifeDays: 21, hsnCode: "0407", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: false, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "R0000010", minimumOrderQty: 1, recommendedPackaging: "Clamshell", qualityChecks: "Freshness float test, visual grading" },
  { skuPrefix: "FR3SH-R-0020", zoneCode: "R", category: "Eggs", subcategory: "Quail Eggs", productName: "Organic Quail Eggs", grade: "Premium", form: "Whole", defaultUnit: "dozen", storageType: "Refrigerated", shelfLifeDays: 14, hsnCode: "0407", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "R0000020", minimumOrderQty: 2, recommendedPackaging: "Clamshell", qualityChecks: "Freshness, visual grading" },
  { skuPrefix: "FR3SH-S-0001", zoneCode: "S", category: "Meat & Poultry", subcategory: "Country Chicken", productName: "Organic Country Chicken - Whole", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 3, hsnCode: "0207", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "S0000001", minimumOrderQty: 1, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, microbiological test, freshness" },
  { skuPrefix: "FR3SH-S-0020", zoneCode: "S", category: "Meat & Poultry", subcategory: "Goat Meat", productName: "Organic Goat Meat - Curry Cut", grade: "Standard", form: "Cut", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 3, hsnCode: "0204", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "S0000020", minimumOrderQty: 0.5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Microbiological test, freshness, batch traceability" },
  { skuPrefix: "FR3SH-S-0040", zoneCode: "S", category: "Meat & Poultry", subcategory: "Organic Chicken", productName: "Organic Broiler Chicken - Whole", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 3, hsnCode: "0207", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "S0000040", minimumOrderQty: 1, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, microbiological test, freshness" },
  { skuPrefix: "FR3SH-T-0001", zoneCode: "T", category: "Seafood", subcategory: "Fresh Fish", productName: "Fresh Rohu Fish - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 2, hsnCode: "0302", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: false, seasonal: false, mainSeason: "Year-round", stateAvailability: "West Bengal, AP", supplierType: "Farmer/FPO", barcodeSkuCode: "T0000001", minimumOrderQty: 1, recommendedPackaging: "Vacuum Pack", qualityChecks: "Freshness, sensory evaluation, microbiological test" },
  { skuPrefix: "FR3SH-T-0020", zoneCode: "T", category: "Seafood", subcategory: "Prawns", productName: "Organic Freshwater Prawns - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 2, hsnCode: "0306", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Kerala, AP", supplierType: "Farmer/FPO", barcodeSkuCode: "T0000020", minimumOrderQty: 0.5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, freshness, microbiological test" },
  { skuPrefix: "FR3SH-T-0040", zoneCode: "T", category: "Seafood", subcategory: "Pomfret", productName: "Fresh Pomfret - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Refrigerated", shelfLifeDays: 2, hsnCode: "0302", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: false, seasonal: false, mainSeason: "Year-round", stateAvailability: "Mumbai, Goa", supplierType: "Farmer/FPO", barcodeSkuCode: "T0000040", minimumOrderQty: 0.5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Freshness, sensory evaluation" },
  { skuPrefix: "FR3SH-U-0001", zoneCode: "U", category: "Mushrooms", subcategory: "Button Mushroom", productName: "Organic Button Mushroom - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 7, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Himachal, Uttarakhand", supplierType: "Farmer/FPO", barcodeSkuCode: "U0000001", minimumOrderQty: 1, recommendedPackaging: "Clamshell", qualityChecks: "Organic certificate, freshness, visual grading" },
  { skuPrefix: "FR3SH-U-0020", zoneCode: "U", category: "Mushrooms", subcategory: "Oyster Mushroom", productName: "Organic Oyster Mushroom - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Telangana, Karnataka", supplierType: "Farmer/FPO", barcodeSkuCode: "U0000020", minimumOrderQty: 0.5, recommendedPackaging: "Clamshell", qualityChecks: "Freshness, organic certificate" },
  { skuPrefix: "FR3SH-U-0040", zoneCode: "U", category: "Mushrooms", subcategory: "Shiitake Mushroom", productName: "Organic Shiitake Mushroom - Premium", grade: "Premium", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 7, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Northeast India", supplierType: "Farmer/FPO", barcodeSkuCode: "U0000040", minimumOrderQty: 0.5, recommendedPackaging: "Clamshell", qualityChecks: "Organic certificate, freshness, visual grading" },
  { skuPrefix: "FR3SH-V-0001", zoneCode: "V", category: "Microgreens & Sprouts", subcategory: "Alfalfa Sprouts", productName: "Organic Alfalfa Sprouts - Premium", grade: "Premium", form: "Live", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "V0000001", minimumOrderQty: 0.1, recommendedPackaging: "Clamshell", qualityChecks: "Organic certificate, freshness, microbiological check" },
  { skuPrefix: "FR3SH-V-0020", zoneCode: "V", category: "Microgreens & Sprouts", subcategory: "Broccoli Sprouts", productName: "Organic Broccoli Sprouts - Premium", grade: "Premium", form: "Live", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "V0000020", minimumOrderQty: 0.1, recommendedPackaging: "Clamshell", qualityChecks: "Freshness, organic certificate" },
  { skuPrefix: "FR3SH-V-0040", zoneCode: "V", category: "Microgreens & Sprouts", subcategory: "Sunflower Microgreens", productName: "Organic Sunflower Microgreens - Premium", grade: "Premium", form: "Live", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "V0000040", minimumOrderQty: 0.1, recommendedPackaging: "Clamshell", qualityChecks: "Freshness, organic certificate" },
  { skuPrefix: "FR3SH-W-0001", zoneCode: "W", category: "Edible Flowers", subcategory: "Banana Flower", productName: "Organic Banana Flower - Standard", grade: "Standard", form: "Whole", defaultUnit: "kg", storageType: "Cold", shelfLifeDays: 5, hsnCode: "0709", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Kerala, TN", supplierType: "Farmer/FPO", barcodeSkuCode: "W0000001", minimumOrderQty: 0.5, recommendedPackaging: "Clamshell", qualityChecks: "Freshness, visual grading" },
  { skuPrefix: "FR3SH-W-0010", zoneCode: "W", category: "Edible Flowers", subcategory: "Hibiscus", productName: "Organic Hibiscus - Dried - Standard", grade: "Standard", form: "Dried", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Tamil Nadu", supplierType: "Farmer/FPO", barcodeSkuCode: "W0000010", minimumOrderQty: 100, recommendedPackaging: "Paper Pouch", qualityChecks: "Moisture, organic certificate" },
  { skuPrefix: "FR3SH-W-0020", zoneCode: "W", category: "Edible Flowers", subcategory: "Rose Petals", productName: "Organic Rose Petals - Dried - Premium", grade: "Premium", form: "Dried", defaultUnit: "g", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "0910", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Kannauj, UP", supplierType: "Farmer/FPO", barcodeSkuCode: "W0000020", minimumOrderQty: 50, recommendedPackaging: "Glass Jar", qualityChecks: "Moisture, organic certificate, aroma check" },
  { skuPrefix: "FR3SH-X-0001", zoneCode: "X", category: "Processed Foods", subcategory: "Fruit Jam", productName: "Organic Mango Jam - No Added Sugar", grade: "Premium", form: "Processed", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "2007", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "X0000001", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "Brix value, pH, organic certificate, preservative-free check" },
  { skuPrefix: "FR3SH-X-0020", zoneCode: "X", category: "Processed Foods", subcategory: "Peanut Butter", productName: "Organic Peanut Butter - Crunchy", grade: "Standard", form: "Paste", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 365, hsnCode: "2008", gstPercent: "12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "X0000020", minimumOrderQty: 0.5, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, aflatoxin test, moisture" },
  { skuPrefix: "FR3SH-X-0040", zoneCode: "X", category: "Processed Foods", subcategory: "Millet Cookies", productName: "Organic Millet Cookies - Jowar", grade: "Standard", form: "Baked", defaultUnit: "packet", storageType: "Ambient", shelfLifeDays: 90, hsnCode: "1905", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "X0000040", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-Y-0001", zoneCode: "Y", category: "Ready-to-Cook Mixes", subcategory: "Idli Mix", productName: "Organic Idli Mix - Premium", grade: "Premium", form: "Powder", defaultUnit: "packet", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "2106", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "Y0000001", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, microbiological check" },
  { skuPrefix: "FR3SH-Y-0020", zoneCode: "Y", category: "Ready-to-Cook Mixes", subcategory: "Ragi Malt Mix", productName: "Organic Ragi Malt Mix - Standard", grade: "Standard", form: "Powder", defaultUnit: "packet", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "2106", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "Y0000020", minimumOrderQty: 5, recommendedPackaging: "Vacuum Pack", qualityChecks: "Organic certificate, moisture" },
  { skuPrefix: "FR3SH-Y-0040", zoneCode: "Y", category: "Ready-to-Cook Mixes", subcategory: "Khichdi Mix", productName: "Organic Khichdi Mix - Masala", grade: "Standard", form: "Blend", defaultUnit: "packet", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "2106", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "Y0000040", minimumOrderQty: 5, recommendedPackaging: "Food-grade Pouch", qualityChecks: "Organic certificate, moisture, visual grading" },
  { skuPrefix: "FR3SH-Z-0001", zoneCode: "Z", category: "Condiments & Misc Food", subcategory: "Rock Salt", productName: "Himalayan Rock Salt - Pink - Premium", grade: "Premium", form: "Chunks", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 1825, hsnCode: "2501", gstPercent: "0/5", fssaiRequired: true, organicCertRequired: false, seasonal: false, mainSeason: "Year-round", stateAvailability: "Multiple", supplierType: "Farmer/FPO", barcodeSkuCode: "Z0000001", minimumOrderQty: 1, recommendedPackaging: "Paper Pouch", qualityChecks: "Mineral content test, visual grading" },
  { skuPrefix: "FR3SH-Z-0020", zoneCode: "Z", category: "Condiments & Misc Food", subcategory: "Apple Cider Vinegar", productName: "Organic Apple Cider Vinegar - With Mother", grade: "Premium", form: "Liquid", defaultUnit: "litre", storageType: "Ambient", shelfLifeDays: 730, hsnCode: "2209", gstPercent: "12/18", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "Himachal", supplierType: "Farmer/FPO", barcodeSkuCode: "Z0000020", minimumOrderQty: 1, recommendedPackaging: "Glass Bottle", qualityChecks: "Organic certificate, acidity test, with-mother verification" },
  { skuPrefix: "FR3SH-Z-0040", zoneCode: "Z", category: "Condiments & Misc Food", subcategory: "Tamarind Paste", productName: "Organic Tamarind Paste - Standard", grade: "Standard", form: "Paste", defaultUnit: "kg", storageType: "Ambient", shelfLifeDays: 180, hsnCode: "2008", gstPercent: "5/12", fssaiRequired: true, organicCertRequired: true, seasonal: false, mainSeason: "Year-round", stateAvailability: "AP, TN", supplierType: "Farmer/FPO", barcodeSkuCode: "Z0000040", minimumOrderQty: 1, recommendedPackaging: "Glass Jar", qualityChecks: "Organic certificate, moisture, visual grading" },
];

async function seedUser() {
  const existing = await WarehouseUser.findOne({ email: "manager@gmail.com" });
  if (existing) {
    console.log("Manager user already exists, skipping");
    return;
  }
  const passwordHash = await bcrypt.hash("test@1234", 12);
  await WarehouseUser.create({
    name: "Warehouse Manager",
    email: "manager@gmail.com",
    passwordHash,
    role: "Warehouse Manager",
    isActive: true,
    warehouseId: "main",
  });
  console.log("✅ Created default manager user: manager@gmail.com / test@1234");
}

async function seedLocations() {
  const existing = await WarehouseLocation.countDocuments({ type: "zone" });
  if (existing > 0) {
    console.log("Zones already seeded, skipping");
    return;
  }

  const storageTypeMap: Record<string, string> = {
    Ambient: "Ambient",
    Cold: "Cold",
    Cool: "Cool",
    Refrigerated: "Refrigerated",
  };

  for (const zone of ZONES) {
    await WarehouseLocation.create({
      type: "zone",
      code: zone.code,
      name: zone.name,
      zoneCode: zone.code,
      storageType: storageTypeMap[zone.type] ?? "Ambient",
      temperatureRange: TEMP_MAP[zone.type] ?? "18–25°C",
      productCategoryMapping: [zone.name],
      warehouseId: "main",
      currentOccupancy: 0,
    });
  }
  console.log(`✅ Seeded ${ZONES.length} warehouse zones (A–Z)`);
}

async function seedProducts() {
  const existing = await WMSProductCatalog.countDocuments();
  if (existing > 0) {
    console.log(`Products already seeded (${existing} docs), skipping`);
    return;
  }

  await WMSProductCatalog.insertMany(SEED_PRODUCTS.map(p => ({ ...p, isActive: true })));
  console.log(`✅ Seeded ${SEED_PRODUCTS.length} products (3 per zone, all 26 zones)`);
}

async function main() {
  await connect();
  await seedUser();
  await seedLocations();
  await seedProducts();
  console.log("\n🌿 FR3SH WMS seed complete");
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
